- src/CSS/index.css
I modified the `index.css` file to modify the **color of the scrollbar** so that it matches well with the theme of the website
The present look of the `index.html`
The present look of the `studyroom.html`
> Customized the scrollbar to make it match the theme of the website

- index.html
- public/studyroom.html
Hey! i just added the discord link in your **every web pages**!
> Added the given discord link in every webpage

- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
> Added all links

- index.html
I have added link in index.html file.
> link added

- index.html
I have added a discord link in index.html file.
> discord link added

- index.html
Fixed various grammatical errors and did proper formatting of the site's main page for better readability.
> fix grammatical errors and formatting

- src/pages/academics/csit.html
I have added one PYQ book of GATE.
> GATE BOOK ADDED

- src/pages/dsa_sheet/main.html
> Created a webpage containing all the famous DSA Sheets

- index.html
- src/CSS/index.css
- src/JS/index.js
- src/pages/development/main.html
Hi, I took some liberty and made few changes to the Content in the page and scrollbar width.
> Closes #51, #53, #55 and #56 with few minor changes.

- index.html
- src/CSS/index.css
altered the button text to be white, and only when a button is hovered over does the background color change to dark blue.
> made all buttons' backgrounds dark blue when hovering

- public/index.html
- src/CSS/index.css
Close #44 
I changed the color of the text in the _**Join Study Room**_ button so that it looks a bit better
Problem faced:
- many buttons had the same class name and hence changing the name with the class selector in CSS was not a viable option
Problem Appearance
-
>I changed the text to orange to show all the different elements that are affected due to it
Measures to overcome:
- I add an id (join_study_room) to the button so that it would be possible to change **only** the color of text in that button
Final Output
-
> Contrast in button text #44

- index.html
- src/CSS/components-css/footer.css
> added hover effect to the social icons

- src/CSS/components-css/navbar.css
- src/CSS/index.css
> Show menu at 991px instead of 700px | 2. Add overflow-x: hidden

- public/studyroom.html
> fixed the typo in the study room section

- src/pages/academics/syllabus.html
> removed extra navs in syllabus.html

- index.html
- src/CSS/components-css/footer.css
I have Improved hover effect on the Contact Us buttons
This is the final hover effect we will be looking after merging **( INDIVIDUALLY )**
Advantages: 
- Bold and eye-catching
- Will help to uniquely identify while hovering while dark mode ( in Future )
- Good performance Desktop, Tablet, Mobile ( Responsive )
- Its code is not affecting other section code
> Updated Contact Us icons under Issue#73

- src/CSS/index.css
I have changed the size of Image and edited the respective buttons and added hover effect on discord button also
#85
> Improved UI of the Home Page

- index.html
- src/CSS/academics/main.css
- src/CSS/components-css/about.css
- src/CSS/components-css/faq.css
- src/CSS/components-css/footer.css
- src/CSS/components-css/main.css
- src/CSS/development/main.css
- src/CSS/index.css
- src/CSS/interview/main.css
- src/pages/academics/main.html
- src/pages/development/main.html
- src/pages/interviewPrep/main.html
I Dilpreet Singh under SSOC 2022 has solved isuue 86. But I haven't added the night mode effect yet . I am working on it and I will be soon completing that task also.
> #86 issue solved . 

- index.html
- public/studyroom.html
> Added meta tags for better SEO

- index.html
- public/studyroom.html
- src/CSS/development/main.css
- src/CSS/index.css
- src/JS/index.js
- src/pages/academics/csit.html
- src/pages/academics/main.html
- src/pages/academics/syllabus.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
- src/pages/dsa_sheet/main.html
- src/pages/subscribe.html
Fixed some small bugs in the CSS.
Fixed loading animation in index page
Responsiveness in the Development page.
> Fixed #100 #111 #112.

- index.html
- public/studyroom.html
- src/CSS/development/main.css
- src/CSS/index.css
- src/JS/index.js
- src/pages/academics/csit.html
- src/pages/academics/main.html
- src/pages/academics/syllabus.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
- src/pages/dsa_sheet/main.html
- src/pages/subscribe.html
> Revert "Fixed #100 #111 #112."

- index.html
- public/studyroom.html
- src/CSS/development/main.css
- src/CSS/index.css
- src/JS/index.js
- src/pages/academics/csit.html
- src/pages/academics/main.html
- src/pages/academics/syllabus.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
- src/pages/dsa_sheet/main.html
- src/pages/subscribe.html
> Revert "Revert "Fixed #100 #111 #112.""

- index.html
- public/studyroom.html
- src/JS/index.js
When clicked on Theme Icon, it will change between Sun and Moon for Light and Dark themes respectively.
> Some changes to the Theme Icon and few errors in study room nav.

- index.html
- public/index.html
- public/studyroom.html
- src/CSS/components-css/footer.css
- src/pages/academics/csit.html
- src/pages/academics/main.html
- src/pages/academics/syllabus.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
- src/pages/dsa_sheet/main.html
- src/pages/interviewPrep/main.html
> Issue #102 fixed  [FOOTER UPDATED]

- public/index.html
I have removed faq-btn and faq-content because they were getting enabled when toggling the faq button. There were no changes by removing these classes but the +/- option is fixed.
> Removed classes for fixing toggle of +/- in faq section

- index.html
- src/CSS/components-css/faq.css
- src/JS/main(index).js
- src/JS/main_nav.js
- src/JS/main_res_nav.js
- src/pages/academics/csit.html
- src/pages/academics/main.html
- src/pages/development/main.html
Navigation Issue Fixed (Dark Mode) and Responsive Navbar Issue Fixed.
> Navigation Issue Fixed (Dark Mode) and Responsive Navbar Issue Fixed

- src/CSS/academics/csit.css
- src/CSS/academics/main.css
- src/CSS/components-css/main.css
- src/pages/academics/csit.html
https://user-images.githubusercontent.com/84625838/184113576-8efc011c-303c-42e1-b2f9-d2c4e2163ba8.png
> Improvement in resources section #104

- index.html
- public/studyroom.html
- src/pages/academics/main.html
- src/pages/development/web.html
- src/pages/interviewPrep/main.html
1) Made grammatical corrections and improved vocabulary for the main content in index.html 
2) Updated indentations and silly errors in abbreviations.
3) Upgraded content design for Studyroom.html
4) Added professional tone to the academics.html
5) Polished the educational content on website development notes.
6) Cleared errors on the interview-prep.html.
> Solved issue #108 - Multiple MISSPELLINGS

- src/pages/academics/civil.html
- src/pages/academics/electrical.html
- src/pages/academics/electronic.html
- src/pages/academics/main.html
- src/pages/academics/mechanical.html
each pages are created but data is missing, it will be added after the details will be provided.
> pages missing of electrical, mechanical, civil and electronics #132

- src/CSS/index.css
Make changes in index.css. Made new media queries related to the width required and some modifications to the image as it does not fit well with the heading alignment.
> Fixed the responsiveness of the heading acadmeia

- index.html
> text and ui update(issue #84)

- index.html
- src/CSS/components-css/about.css
- src/CSS/components-css/faq.css
- src/CSS/components-css/footer.css
- src/CSS/components-css/main.css
- src/CSS/components-css/navbar.css
- src/CSS/index.css
I worked on the font-colors in dark theme only!! And doesn't anything in light theme!
Before:
After:
Is it fine :/
> updated the font-colors of home page

- src/CSS/index.css
- src/pages/development/blockchain.html
My pull request for issue #83 
I've added resources in the form of documentation, books and also included some communities to be part of. Can You please review this PR
Mail-id: pramodhr181@gmail.com
> Add resources for the blockchain section under the development section of the website #83

- index.html
- src/CSS/components-css/about.css
- src/CSS/components-css/footer.css
- src/CSS/index.css
Fixes in Footer icons Transient Color combination with Dark Mode - footer.css
Before- 
After-
Added Button Hover Transitions to About section - about.css
Before-
After- 
Fixed Discord logo color combination with Dark/Light modes - index.css
Before-
After-
Also Improved the HTML Indentations
> Footer, About, Index CSS improved for issue "Need A fix for Color Coordination and Transient Effects to some buttons #137"

- README.md
Hi Sir/Madam,
Fixed typos and grammatical mistakes in README.md. Thanks.
> Fixed typos and grammatical mistakes in README.md

- index.html
- src/CSS/index.css
This is my PR to issue #164.
I've added a feedback section in the landing page of the website.
Mail-Id: pramodhr181@gmail.com
Devfolio Username: Prahmodh_Raj
> Added a feedback section in the website: Resolved issue #164

- src/CSS/components-css/main.css
- src/CSS/development/main.css
- src/pages/development/main.html
earlier it was 
now 
i have added space and double inverted commas to the word "Project".
> added space and double quotes to the word Project in development part

- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/ml.html
- src/pages/development/web.html
Added Favicons In android.html blockchain.html devops.html ml.html web.html
> Added Favicons

- src/CSS/components-css/faq.css
- src/JS/main.js
- src/pages/interviewPrep/main.html
Improved Video Alignment and responsiveness and added video in CS Fundamentals.
@narayan954 Now I have improved the aligment on hovering and added lectures in CS Fundamentals. #150
> Improved Video Alignment and responsiveness and added video in CS Fundamentals

- src/pages/interviewPrep/main.html
Issue No : #171 
- I have added OOPS section under Compputer Science Fundamentals in Interview Preparation.
- I have also added related video inks and notes.
- I have maintained the pattern, color and style of the webpage.
- The web page remains stable after my changes.
> Adding OOPS section under CS Fundamentals in Interview Preparation

- src/pages/academics/civil.html
- src/pages/academics/csit.html
- src/pages/academics/electrical.html
- src/pages/academics/electronic.html
- src/pages/academics/mechanical.html
- src/pages/academics/syllabus.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/ml.html
- src/pages/development/web.html
the address was wrong for the image which is uploaded in the src source folder that's why it was not loaded at pages but now it's working perfectly
##BEFORE
##AFTER
> Fixed the image error (issue #183)

- src/CSS/index.css
> added border and hover effect to feedback section

- public/studyroom.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
Nav. Bar is fixed in all subpages of development and fixed dark mode.
Before
After
Before
After
@myhacktech @tier3guy Kindly Review it.
Issue Solved :- #165
> Nav. Bar is fixed in all subpages of development and fixed dark mode

- index.html
- src/CSS/components-css/faq.css
- src/CSS/components-css/main.css
- src/CSS/index.css
Main Page is not Fixed, UI and responsiveness improved.
Issue Solved :- #185 
Some SS:-
5).png…]()
@myhacktech Kindly Review it.
@tier3guy
> Main Page is now Fixed, UI and responsiveness improved

- src/JS/main.js
- src/pages/interviewPrep/main.html
resolving the issue #57 
search functionality added in interview page
> Aritra pr--- solving issue #57

- README.md
Fixed many typos and grammatical errors, poor formatting and edited README.md of the project!
> heavily edited readme.md

- index.html
- src/CSS/components-css/footer.css
- src/CSS/components-css/main.css
- src/CSS/index.css
> Please review it. There is some mistake in the footer section. I will fix it.
> changes done in main and footer section in light theme

- index.html
- src/CSS/components-css/about.css
- src/CSS/components-css/footer.css
- src/CSS/components-css/main.css
- src/CSS/index.css
- src/pages/academics/civil.html
- src/pages/academics/csit.html
- src/pages/academics/electrical.html
- src/pages/academics/electronic.html
- src/pages/academics/main.html
- src/pages/academics/mechanical.html
- src/pages/academics/syllabus.html
- src/pages/development/android.html
- src/pages/development/blockchain.html
- src/pages/development/devops.html
- src/pages/development/main.html
- src/pages/development/ml.html
- src/pages/development/web.html
- src/pages/dsa_sheet/main.html
- src/pages/interviewPrep/main.html
Please review it once. It requires much more changes in the subpages for the footer section. Next, I want to attach some necessary documents to it.
> Some UI of dark theme as well and footer section has updated

- src/CSS/components-css/about.css
- src/CSS/components-css/faq.css
- src/CSS/components-css/footer.css
- src/CSS/components-css/main.css
- src/CSS/components-css/navbar.css
- src/CSS/index.css
> responsiveness done in main pages

- .vscode/launch.json
- index.html
- src/CSS/components-css/footer.css
I have resolved the overlapping of buy me a coffee icon.
> Fix: Buy me a coffee overlap resolved
